### ISSUE TITLE
error order incorrect

### ISSUE THREAD

**Issue by jeroen** [r-lib/evaluate#28]
When running a function that throws plots and then throws an error, the plot appears after the error in the output:

```
library(evaluate)
test <- function(){
    plot(rnorm(100))
    stop("this is an error!")
}

out <- evaluate("test()")
lapply(out, is)

[[1]]
[1] "source"

[[2]]
[1] "simpleError"

[[3]]
[1] "recordedplot" "oldClass" 
```

**Comment by hadley** [comment]
Looks like this is still a problem.

**Comment by hadley** [comment]
Can see this problem in an Rmd/qmd too:

````
```{r}
#| error: true
test <- function(){
  plot(rnorm(100))
  stop("this is an error!")
}
test()
```
````

I suspect this is because we can only tell when a plot is complete retrospectively, i.e. after a new plot is created or the code finishes.  

...

Or maybe the problem is that the error handler doesn't handle any output before handling the error. If so, that's an easy fix.

**Comment by hadley** [comment]
I see the same problem with `message()` and `warning()` too. More comprehensive test case:

```R
test <- function(){
  plot(1, main = "one")
  message("this is an message!")
  plot(2, main = "two")
  warning("this is a warning")
  plot(3, main = "three")
  stop("this is an error")
}
test()
```
